apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmt-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-adapter
  labels:
    app: tf-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-adapter
  template:
    metadata:
      labels:
        app: tf-adapter
    spec:
      containers:
        - name: tf-adapter
          image: quay.io/ahadas/tf_adapter:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmt-results
              mountPath: /results
      volumes:
        - name: tmt-results
          persistentVolumeClaim:
            claimName: tmt-results
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-artifacts
  labels:
    app: tf-artifacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-artifacts
  template:
    metadata:
      labels:
        app: tf-artifacts
    spec:
      containers:
        - name: tf-artifacts
          image: quay.io/ahadas/tf_artifacts:latest
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: tmt-results
              mountPath: /srv/results
      volumes:
        - name: tmt-results
          persistentVolumeClaim:
            claimName: tmt-results
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-api
  name: tf-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tf-adapter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifacts
  name: artifacts
spec:
  ports:
  - port: 873
    protocol: TCP
    targetPort: 8090
  selector:
    app: tf-artifacts
