apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmt-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-adapter
  labels:
    app: tf-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-adapter
  template:
    metadata:
      labels:
        app: tf-adapter
    spec:
      containers:
        - name: tf-adapter
          image: quay.io/ahadas/tf_adapter:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tmt-results
              mountPath: /results
        - name:
          image: quay.io/ahadas/tf_artifacts:latest
          ports:
            - containerPort: 873
          volumeMounts:
            - name: tmt-results
              mountPath: /results
      volumes:
        - name: tmt-results
          persistentVolumeClaim:
            claimName: tmt-results
