apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tc-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-console
  labels:
    app: test-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-console
  template:
    metadata:
      labels:
        app: test-console
    spec:
      containers:
        - name: test-console
          image: quay.io/ahadas/test-console:latest
          ports:
            - containerPort: 8000
          securityContext:
            privileged: true
          env:
            - name: TESTING_FARM_API_URL
              value: http://tf-api.demo.svc.cluster.local
            - name: TF_RESULTS_URL
              value: http://tf-adapter.demo.svc.cluster.local/v0.1/testing-farm
            - name: TF_RSYNC_ARTIFACTS_URL
              value: rsync://artifacts.demo.svc.cluster.local/artifacts
          volumeMounts:
            - name: tc-db
              mountPath: /var/lib/test-console
      volumes:
        - name: tc-db
          persistentVolumeClaim:
            claimName: tc-db
