apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmt-results
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adapter-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tf-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tf-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tf-api
subjects:
- kind: ServiceAccount
  name: tf-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tf-api
rules:
- apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
  verbs:
    - create
    - get
- apiGroups:
    - jumpstarter.dev
  resources:
    - exporters
  verbs:
    - list
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-api
  labels:
    app: tf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-api
  template:
    metadata:
      labels:
        app: tf-api
    spec:
      containers:
        - name: tf-api
          image: quay.io/ahadas/tf_adapter:latest
          ports:
            - containerPort: 8080
          env:
            - name: TF_API_URL
              value: https://api.dev.testing-farm.io
            - name: IMAGE
              value: https://autosd.sig.centos.org/AutoSD-9/nightly/TI/auto-osbuild-j784s4evm-autosd9-qa-regular-aarch64-1707518541.e6b348fc.raw.xz
            - name: TIMEOUT
              value: 3h0m0s
            - name: PIPELINE
              value: test-pipeline
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: adapter-db
              mountPath: /srv/db
      serviceAccountName: tf-api
      volumes:
        - name: adapter-db
          persistentVolumeClaim:
            claimName: adapter-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifacts
  labels:
    app: artifacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifacts
  template:
    metadata:
      labels:
        app: artifacts
    spec:
      containers:
        - name: artifacts
          image: quay.io/ahadas/tf_artifacts:latest
          ports:
            - containerPort: 8090 # rsync
            - containerPort: 8080 # http server
          volumeMounts:
            - name: tmt-results
              mountPath: /srv/results
          env:
            - name: TF_RESULTS_URL
              value: https://artifacts.osci.redhat.com
      volumes:
        - name: tmt-results
          persistentVolumeClaim:
            claimName: tmt-results
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-api
  name: tf-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tf-api
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tf-api
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tf-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artifacts
  name: artifacts
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: server
  - port: 873
    protocol: TCP
    targetPort: 8090
    name: rsync
  selector:
    app: artifacts
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: artifacts
  name: artifacts
spec:
  port:
    targetPort: server
  to:
    kind: Service
    name: artifacts
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsync-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rsync-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rsync-rolebinding
subjects:
  - kind: ServiceAccount
    name: rsync-client
roleRef:
  kind: Role
  name: rsync-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: rsync-secret
  annotations:
    kubernetes.io/service-account.name: rsync-client
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rsync-client
secrets:
  - name: rsync-secret
