apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-console-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-console
  labels:
    app: test-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-console
  template:
    metadata:
      labels:
        app: test-console
    spec:
      containers:
        - name: test-console
          image: quay.io/ahadas/test-console:latest
          ports:
            - containerPort: 8000
          env:
            - name: TF_OCP_API_URL
              value: http://tf-api-demo.apps.zmeya.rh-internal.ocm
            - name: TF_OCP_RESULTS_URL
              value: http://artifacts-demo.apps.zmeya.rh-internal.ocm
            - name: KUBECONFIG
              value: /etc/kube/kubeconfig
          volumeMounts:
            - name: test-console-storage
              mountPath: /var/lib/test-console
            - name: kubeconfig-secret-volume
              mountPath: /etc/kube/kubeconfig
              subPath: kubeconfig
      volumes:
        - name: test-console-storage
          persistentVolumeClaim:
            claimName: test-console-storage
        - name: kubeconfig-secret-volume
          secret:
            secretName: kubeconfig-secret
