FROM fedora:latest

RUN dnf -y install rsync python3 python3-pip && \
    dnf clean all

RUN curl -L https://github.com/tektoncd/cli/releases/download/v0.42.0/tektoncd-cli-0.42.0_Linux-ARM64.rpm -o tektoncd-cli.rpm && \
    rpm -Uvh tektoncd-cli.rpm && \
    rm tektoncd-cli.rpm

COPY rsync.config /etc/rsync.config
COPY entrypoint.sh /usr/local/entrypoint.sh
COPY server.py /usr/local/server.py
COPY results.html /usr/local/results.html

RUN chmod +x /usr/local/entrypoint.sh
ENTRYPOINT ["/usr/local/entrypoint.sh"]
