FROM fedora:latest

RUN dnf -y install rsync python3 python3-pip

COPY rsync.config /etc/rsync.config
COPY entrypoint.sh /usr/local/entrypoint.sh
COPY server.py /usr/local/server.py

RUN pip3 install requests
RUN chmod +x /usr/local/entrypoint.sh
ENTRYPOINT ["/usr/local/entrypoint.sh"]
